### ISSUE TITLE
filterDuplicated Error

### ISSUE THREAD

**Issue by Fire-Brand** [jstools/jqlite#30]
Hi, i've recently updated from version 2.19 to 2.24 (latest), and am now getting the following error:

```Uncaught (in promise) TypeError: Cannot assign to read only property '___found___' of 0(…) ``` 
on line ```jqLite.js:949```

the stack trace and devtools look like this:

![jqliteerr](https://cloud.githubusercontent.com/assets/8603744/10515273/55e7c84e-735b-11e5-9eb6-d6e1000de3be.png)

Any idea why does this happens? 
P.S. i'm using [promise-polyfill](https://github.com/taylorhakes/promise-polyfill)

**Comment by jgermade** [comment]
@Fire-Brand first of all, thanks for taking your time and for your feedback!

this issue should be solved in release [v0.2.25](https://github.com/jstools/jqlite/releases/tag/v0.2.25) the bug was introduced in version v0.2.22 where filter implementation was changed to be compliance with jquery version.

Please, let me know if is working fine now. Thanks again!
